### ISSUE TITLE
Issue with multi-docs branch

### ISSUE THREAD

**Issue by zechajw** [BjornTheProgrammer/codemirror-collab-react-codemirror#4]
Hi! I cloned your multi-docs branch and have been trying to run it locally, but I've run into a bug when I try to edit the documents

`index.js:868 Uncaught (in promise) RangeError: Applying change set to a document with the wrong length
    at _ChangeSet.apply (index.js:868:19)
    at get newDoc [as newDoc] (index.js:2274:55)
    at _EditorState.applyTransaction (index.js:2642:34)
    at get state [as state] (index.js:2293:29)
    at _EditorView.update (index.js:6938:24)
    at _EditorView.dispatchTransactions (index.js:6898:28)
    at _EditorView.dispatch (index.js:6920:14)
    at Object.pull (collab.ts:113:15)`
    
Would you happen to know what is causing this issue?

**Comment by BjornTheProgrammer** [comment]
Appreciate the issue! I've actually multiple times tried to replicate this issue over the past few months, but I can never get the issue myself. Would you mind providing a step by step reproduction of this issue?
